import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const repoRoot = findRepoRoot(__dirname);
const specPath = path.join(repoRoot, "generated", "grammar.json");
const grammarPath = path.join(rootDir, "grammar.js");
const fragmentsPath = path.join(rootDir, "generated", "grammar-fragments.js");
const highlightsPath = path.join(rootDir, "queries", "highlights.scm");
const localsPath = path.join(rootDir, "queries", "locals.scm");
const foldsPath = path.join(rootDir, "queries", "folds.scm");
const commentstringPath = path.join(rootDir, "queries", "commentstring.scm");

if (!fs.existsSync(specPath)) {
  throw new Error(`missing generated spec: ${specPath}`);
}

const spec = JSON.parse(fs.readFileSync(specPath, "utf8"));
validateSpec(spec);
const grammarSource = fs.readFileSync(grammarPath, "utf8");
const fragmentsSource = fs.readFileSync(fragmentsPath, "utf8");
const highlightsSource = fs.readFileSync(highlightsPath, "utf8");
const localsSource = fs.readFileSync(localsPath, "utf8");
const foldsSource = fs.readFileSync(foldsPath, "utf8");
const commentstringSource = fs.readFileSync(commentstringPath, "utf8");

const actionSystem = spec.action_system;
const tokenKindRules = Object.fromEntries(
  (spec.token_kind_rules || []).map((tkr) => [tkr.kind, tkr]),
);

// ---- Source provenance checks ----

checkIncludes(grammarSource, 'require("./generated/grammar-fragments")', "grammar.js must load generated grammar fragments");
checkAutoGenerated(fragmentsSource, "generated grammar fragments");
checkAutoGenerated(highlightsSource, "highlights.scm");
checkAutoGenerated(localsSource, "locals.scm");
checkAutoGenerated(foldsSource, "folds.scm");
checkAutoGenerated(commentstringSource, "commentstring.scm");
checkIncludes(
  commentstringSource,
  `commentstring "${spec.line_comment_prefix} %s"`,
  "commentstring.scm must match the exported line comment prefix",
);

// ---- Declaration & line rule checks ----

for (const decl of spec.declarations || []) {
  const declNode = decl.node_name;

  checkIncludes(fragmentsSource, `"kind": "${decl.kind}"`, `missing declaration fragment for ${decl.kind}`);

  if (decl.body) {
    checkIncludes(foldsSource, `(${declNode}) @fold`, `missing fold entry for ${declNode}`);
  }

  const headerDefs = collectTopLevelDefinitions(decl);
  for (const fieldName of headerDefs) {
    checkIncludes(
      localsSource,
      `(${declNode} ${fieldName}: (identifier) @local.definition)`,
      `missing local definition entry for ${declNode}.${fieldName}`,
    );
  }

  const headerRefs = collectReferences(decl.header || []);
  for (const fieldName of headerRefs) {
    checkIncludes(
      localsSource,
      `(${declNode} ${fieldName}: (identifier) @local.reference)`,
      `missing local reference entry for ${declNode}.${fieldName}`,
    );
  }

  for (const line of decl.body?.lines || []) {
    if (actionSystem && line.node_name === actionSystem.clause_node_name) {
      for (const form of actionSystem.forms || []) {
        for (const fieldName of collectReferences(form.pattern || [])) {
          checkIncludes(
            localsSource,
            `(${actionSystem.clause_node_name} (${actionSystem.expr_node_name} (${form.node_name} ${fieldName}: (identifier) @local.reference)))`,
            `missing local reference entry for ${form.node_name}.${fieldName}`,
          );
        }
      }
      continue;
    }

    for (const fieldName of collectReferences(line.pattern || [])) {
      checkIncludes(
        localsSource,
        `(${line.node_name} ${fieldName}: (identifier) @local.reference)`,
        `missing local reference entry for ${line.node_name}.${fieldName}`,
      );
    }
  }
}

// ---- Highlight checks ----

for (const keyword of collectKeywordTokens(spec)) {
  if (!highlightsSource.includes(JSON.stringify(keyword))) {
    throw new Error(`missing keyword highlight entry for ${keyword}`);
  }
}

for (const pattern of collectStructuralPatterns(spec)) {
  if (!highlightsSource.includes(pattern)) {
    throw new Error(`missing structural highlight entry ${pattern}`);
  }
}

// ---- Helpers ----

function checkIncludes(source, needle, message) {
  if (!source.includes(needle)) {
    throw new Error(message);
  }
}

function findRepoRoot(start) {
  for (let dir = start; ; dir = path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, "go.mod"))) {
      return dir;
    }
    const parent = path.dirname(dir);
    if (parent === dir) {
      throw new Error(`could not find repo root from ${start}`);
    }
  }
}

function validateSpec(spec) {
  const requiredArrays = [
    "declarations",
    "reserved_keywords",
    "punctuation_tokens",
    "token_kind_rules",
  ];
  for (const key of requiredArrays) {
    if (!Array.isArray(spec[key])) {
      throw new Error(`invalid grammar.json: ${key} must be an array`);
    }
  }
  for (const key of ["identifier_pattern", "number_pattern", "string_pattern", "line_comment_prefix"]) {
    if (typeof spec[key] !== "string" || spec[key] === "") {
      throw new Error(`invalid grammar.json: ${key} must be a non-empty string`);
    }
  }
  for (const decl of spec.declarations) {
    if (typeof decl.kind !== "string" || typeof decl.keyword !== "string" || !Array.isArray(decl.header)) {
      throw new Error("invalid grammar.json: each declaration needs kind, keyword, and header");
    }
    for (const line of decl.body?.lines || []) {
      if (typeof line.node_name !== "string" || !Array.isArray(line.pattern)) {
        throw new Error(`invalid grammar.json: malformed line rule in ${decl.kind}`);
      }
    }
  }
}

function checkAutoGenerated(source, label) {
  checkIncludes(source, "AUTO-GENERATED from generated/grammar.json", `${label} must be generated from generated/grammar.json`);
}

function collectTopLevelDefinitions(decl) {
  const out = [];
  const header = decl.header || [];

  for (let i = 0; i < header.length; i++) {
    const matcher = header[i];
    const hasLeadingKeyword = header.slice(0, i).some((m) => m.type === "kw");
    if (!hasLeadingKeyword) continue;

    if (matcher.type === "ident" && matcher.name) {
      out.push(matcher.name);
      break;
    }
    if (matcher.type === "list" && matcher.name) {
      out.push(matcher.name);
      break;
    }
  }

  return out;
}

function collectReferences(matchers) {
  const out = [];
  collectReferencesInto(matchers, out);
  return [...new Set(out)];
}

function collectReferencesInto(matchers, out) {
  for (const m of matchers || []) {
    switch (m.type) {
      case "ref":
        if (m.name) {
          out.push(m.name);
        }
        break;
      case "list":
        if (m.item) {
          collectReferencesInto([m.item], out);
        }
        break;
      case "opt":
        collectReferencesInto(m.inner || [], out);
        break;
      default:
        break;
    }
  }
}

function collectKeywordTokens(spec) {
  const out = new Set();

  for (const decl of spec.declarations || []) {
    collectKeywordsFromMatchers(decl.header || [], out);
    if (decl.body?.lines) {
      for (const line of decl.body.lines) {
        collectKeywordsFromMatchers(line.pattern || [], out);
      }
    }
  }

  return [...out].sort();
}

function collectKeywordsFromMatchers(matchers, out) {
  for (const m of matchers || []) {
    switch (m.type) {
      case "kw":
        for (const token of String(m.text || "")
          .split(/\s+/)
          .filter(Boolean)) {
          out.add(token);
        }
        break;
      case "opt":
        collectKeywordsFromMatchers(m.inner || [], out);
        break;
      case "list":
        if (m.separator) {
          out.add(m.separator);
        }
        if (m.item) {
          collectKeywordsFromMatchers([m.item], out);
        }
        break;
      default:
        break;
    }
  }
}

function collectStructuralPatterns(spec) {
  const out = [];

  for (const decl of spec.declarations || []) {
    if (!decl.body?.lines) continue;
    for (const line of decl.body.lines) {
      if (actionSystem && line.node_name === actionSystem.clause_node_name) {
        continue;
      }
      walkPatternForDrift(line.pattern || [], line.node_name, out);
    }
  }

  if (actionSystem) {
    for (const form of actionSystem.forms || []) {
      walkPatternForDrift(form.pattern || [], form.node_name, out);
    }
  }

  return out;
}

function walkPatternForDrift(matchers, nodeName, out) {
  for (const m of matchers || []) {
    switch (m.type) {
      case "tok": {
        if (!m.name) break;
        const tkr = tokenKindRules[m.kind];
        if (!tkr) break;
        if (tkr.values?.length > 0) {
          out.push(`(${nodeName} ${m.name}: (${tkr.rule}) @function.builtin)`);
        }
        if (tkr.fallback) {
          out.push(`(${nodeName} ${m.name}: (${tkr.fallback}) @function.builtin)`);
        } else if (!tkr.values?.length) {
          out.push(`(${nodeName} ${m.name}: (${tkr.rule}) @function.builtin)`);
        }
        break;
      }
      case "enum":
        if (m.name) {
          out.push(`(${nodeName} ${m.name}: (identifier) @constant)`);
        }
        break;
      case "opt":
        walkPatternForDrift(m.inner || [], nodeName, out);
        break;
      case "list":
        if (m.item) {
          walkPatternForDrift([m.item], nodeName, out);
        }
        break;
      default:
        break;
    }
  }
}
